defaults:
  - _self_
  - benchmark: hotpotqa
  - agent: expel
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

ai_name: ${benchmark.ai_name}
agent_type: ${agent.name}
log_dir: logs
run_name: run
testing: true
resume: false
auto_resume: false

# Unified training phase control
run_phase_1: true    # Enable Training Phase 1 (Experience Gathering)
run_phase_2: true    # Enable Training Phase 2 (Insights Extraction)

# remove hydra output files
hydra:  
  output_subdir: null  
  run:  
    dir: .